-- MySQL Script generated by MySQL Workbench
-- Sun Jun  2 23:15:17 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema cp_bd
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema cp_bd
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `cp_bd` DEFAULT CHARACTER SET utf8 ;
USE `cp_bd` ;

-- -----------------------------------------------------
-- Table `cp_bd`.`shops`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cp_bd`.`shops` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `shop` VARCHAR(45) NOT NULL,
  `created_at` TIMESTAMP NULL,
  `updated_at` TIMESTAMP NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cp_bd`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cp_bd`.`users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NOT NULL,
  `lastname` VARCHAR(100) NOT NULL,
  `phone` VARCHAR(13) NOT NULL,
  `nit` VARCHAR(45) NOT NULL,
  `neighborhood` VARCHAR(45) NOT NULL,
  `id_shop` INT NOT NULL,
  `created_at` TIMESTAMP NULL,
  `updated_at` TIMESTAMP NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_users_shops_idx` (`id_shop` ASC),
  CONSTRAINT `fk_users_shops`
    FOREIGN KEY (`id_shop`)
    REFERENCES `cp_bd`.`shops` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
